### ISSUE TITLE
Can't get transactions of a user

### ISSUE THREAD

**Issue by phoenix741** [vanwalj/node-mangopay-sdk#1]
After getting the user (https://api.sandbox.mangopay.com/v2.01/xxxxxx//users/9499412)
When i made 

``` js
return user.Transactions.list({
    page: 1,
    per_page: 100
});
```

The request is https://api.sandbox.mangopay.com/v2.01/xxxxxxx//users/undefined/transactions (no user id).

It's because when _bindUser is called the id of the user is Id and not id. (I think that it's same for all other methods).

Did I do something wrong?

**Comment by vanwalj** [comment]
Hello and thanks for your feedback :)
This module is currently under development, and to be honest I did not expect users already.
But I will fix this within the day, and I'll let you know as soon as everything is okay !

**Comment by vanwalj** [comment]
Heya !
I fixed it and included your 'bug' to the tests.
I've also done small changes to the API (removing the weird plural on models), so the base API is now stable, even if there is lots of features to come.
Please tell me if everything is ok for you :)

**Comment by phoenix741** [comment]
Thanks it work :)

I need to develop an application using mangopay with nodejs, and i found that your module is the best for this. I don't want to rewrite a code that already exists (even if it still under development).

Thanks a lot
