### ISSUE TITLE
Can't get the content of the error.

### ISSUE THREAD

**Issue by phoenix741** [vanwalj/node-mangopay-sdk#2]
Hi,

I try to call user.BankAccount.create to create a bank account and i have an error because the IBAN is invalid.

Unfortunately the error doesn't return the object that i can use to return the error to the client.

```
console.error(body);
return reject(new Error(`Mangopay client error: ${ body.Message }`, body));
```

The second parameter isn't used and can't be read.

I think that it's possible to do :

```
console.error(body);
var error = new Error(`Mangopay client error: ${ body.Message }`);
error.body = body;
return reject(error);
```

Thanks,

**Comment by vanwalj** [comment]
Yeah !
Good idea, will do that by the day !
Thanks for the feedback :)

**Comment by vanwalj** [comment]
Hello !
So now, API errors will throw a dedicated error (At the moment, only two different, but more are to come)
`MangopayError` which is the base class and `ParamError` which you can get on `Mangopay.errors`

Those errors will directly contains Mangopay response body :)
If you have any suggestion, let me know !

For the record, next steps of this SDK are:
- Complete the doc
- Validate parameters

**Comment by phoenix741** [comment]
Thanks it works perfectly :)
